---
plugin: aws_ec2
regions:
  - eu-west-1
keyed_groups:
  - key: tags
    prefix: "tag" # incase you dont want the underscore infornt of the group name
  - key: instance_type
    prefix: instance_type
